### ISSUE TITLE
How to fit on a ScanNet scene?

### ISSUE THREAD

**Issue by BostonLobster** [alievk/npbg#2]
Each ScanNet scene contains RGB-D images, so I can project 2D pixels to 3D point cloud and save them to a `.ply` file. 
But how to modify `path_example.yaml` and `train_example.yaml` to fit the descriptors on this `ply` file?

Any guidelines or suggestions?

**Comment by seva100** [comment]
Most likely, you will only need to modify the `path_example.yaml`. The syntax is:
```yaml
datasets:
    "your_scene_name":
        scene_path: your_scene/your_scene_config.yaml    # path to your scene config -- needs to be filled in separately
        target_path: your_scene/images_undistorted    # path to undistorted images of your scene
        target_name_func: "lambda i: f'{i}.png'"    # lambda which defines the file name format for ground truth picture #i in target_path
```

You'll also need to create `your_scene/your_scene_config.yaml` mentioned above. The structure is:
```yaml
viewport_size: [2160, 3840]    # width, height of your target images
intrinsic_matrix: path/to/scene/intrinsic.txt
view_matrix: path/to/scene/view_matrices.txt
pointcloud: path/to/scene/point_cloud.ply
```

You can look at some examples by downloading the [sample data](https://drive.google.com/open?id=1h0VrTBRyNKUCk3y5GnxhzdA7C6_4ok1Z) provided with the repository.
Hope this helps.
