### ISSUE TITLE
How to train from scratch or fine-tune with multiply scenes datasets?

### ISSUE THREAD

**Issue by xdiyer** [alievk/npbg#23]
I want to train the model with my own dataset from scratch, and also want to fine-tune the model with 2 different scenes datasets as you did in paper about scene editing. Could you tell me how to modify the train.py or release the training code from scratch?Looking forward to your reply.Thank you.

**Comment by seva100** [comment]
Hi @xdiyer, for training from scratch you can just follow the guidelines in the [Fitting descriptors](https://github.com/alievk/npbg#fitting-descriptors) section of the readme. You will only need to modify the configs for your scene (`train_example.yaml`, `paths_example.yaml`, `scene.yaml`). Similarly, for training the network on 2 scenes, you can specify both of them in the paths config under the main section `datasets`. The example would be:

```yaml
datasets:
    "my_scene_1":
         scene_path: scene_1.yaml
         target_path: images_undistorted_1
         target_name_func: "lambda i: f'{i}.png'"
    "my_scene_2":
         scene_path: scene_2.yaml
         target_path: images_undistorted_2
         target_name_func: "lambda i: f'{i}.png'"
```

You can also look at other issues where training on the new scenes is described (e.g. the nice example is [here](https://github.com/alievk/npbg/issues/2)).
